---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webapp.clusterscan.api.io
  resources:
  - clusterscans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.clusterscan.api.io
  resources:
  - clusterscans/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.clusterscan.api.io
  resources:
  - clusterscans/status
  verbs:
  - get
  - patch
  - update
