## Append samples of your project ##
resources:
- cronjob_sample.yaml
- job_sample.yaml
- terrascan.yaml
- kubevious.yaml
- webapp_v1_clusterscan.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
