apiVersion: webapp.clusterscan.api.io/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: kubecontroller
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
spec:
  # TODO(user): Add fields here
